# Generated by Django 6.0.6 on 2026-06-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commentary',
        ),
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name_plural': 'commentaries'},
        ),
    ]
