# Generated by Django 6.0.6 on 2026-06-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_comment_commentary_alter_commentary_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='owner',
            new_name='user',
        ),
    ]
